export const GET_ERRORS = 'GET_ERRORS';
export const GET_LOADING = 'GET_LOADING';
export const GET_SELECT_RATE = 'GET_SELECT_RATE';
export const GET_BASIC_RATES = 'GET_BASIC_RATES';
export const GET_YESTERDAY_RATE = 'GET_YESTERDAY_RATE';
export const GET_NEW_RATE = 'GET_NEW_RATE';
export const GET_YESTERDAY_NEW_RATE = 'GET_YESTERDAY_NEW_RATE';