const CONVERTOR = {
  UPDATE: 'UPDATE_CONVERTOR',
  FROM_BASE: 'SET_FROM_BASE',
  TO_BASE: 'SET_TO_BASE',
  LOADING_CONVERTOR: 'LOADING_CONVERTOR',
  LOADED_CONVERTOR: 'LOADED_CONVERTOR',
  ERROR: 'ERROR_CONVERTOR',
}

const RATES = {
  UPDATE: 'UPDATE_RATES',
  UPDATE_LAST_YEAR: 'UPDATE_LAST_YEAR',
  FROM_RATES: 'SET_FROM_RATES',
  LOADING_RATES: 'LOADING_RATES',
  LOADED_RATES: 'LOADED_RATES',
  LOADING_LAST_YEAR: 'LOADING_LAST_YEAR',
  LOADED_LAST_YEAR: 'LOADED_LAST_YEAR',
  ADD_RATE: 'ADD_RATE',
  ERROR: 'ERROR_RATES',
}

export { CONVERTOR, RATES };