const SET = {
  CURRENCY: 'SET_CURRENCY',
  UPDATE: 'UPDATE_CURRENCY',
  FROM: 'SET_FROM',
  TO: 'SET_TO',
};
const ERROR = {
  SET_ERROR: 'SET_ERROR'
};
const LOADING = {
  IS_LOADING: 'IS_LOADING',
  IS_LOADED: 'IS_LOADED'
}

export { SET, ERROR, LOADING };