export const country  = [
  {
    id: 1,
    title: 'Australia',
    currency: 'Australian Dollar',
    code: 'AUS',
  },
  {
    id: 2,
    title: 'Bulgaria',
    currency: 'Bulgarian Lev',
    code: 'BGR',
  },
  {
    id: 3,
    title: 'BRAZIL',
    currency: 'Brazilian Real',
    code: 'BRA',
  },
  {
    id: 4,
    title: 'CANADA',
    currency: 'Canadian Dollar',
    code:'CAN',
  },
  {
    id: 5,
    title: 'SWITZERLAND',
    currency: 'Swiss Franc',
    code: 'CHE',
  },
  {
    id: 6,
    title: 'CHINA',
    currency: 'Yuan Renminbi',
    code: 'CHN',
  },
  {
    id: 7,
    title: 'CZECH REPUBLIC',
    currency: 'Czech Koruna',
    code: 'CZE',
  },
  {
    id: 8,
    title: 'DENMARK',
    currency: 'Danish Krone',
    code: 'DNK',
  },
  {
    id: 9,
    title: 'EUROPE',
    currency: 'EUR',
    code: 'EU',
  },
  {
    id: 10,
    title: 'UNITED KINGDOM',
    currency: 'Pound Sterling',
    code: 'GBR',
  },
  {
    id: 11,
    title: 'HONG KONG',
    currency: 'Hong Kong Dollar',
    code: 'HKG',
  },
  {
    id: 11,
    title: 'CROATIA',
    currency: 'Kuna',
    code: 'HRV',
  },
  {
    id: 12,
    title: 'HUNGARY',
    currency: 'Forint',
    code: 'HUN',
  },
  {
    id: 13,
    title: 'INDONESIA',
    currency: 'Rupiah',
    code: 'IDN',
  },
  {
    id: 14,
    title: 'ISRAEL',
    currency: 'New Israeli Sheqel',
    code: 'ISR',
  },
  {
    id: 15,
    title: 'INDIA',
    currency: 'Indian Rupee',
    code: 'IND',
  },
  {
    id: 16,
    title: 'ICELAND',
    currency: 'Iceland Krona',
    code: 'ISL',
  },
  {
    id: 17,
    title: 'JAPAN',
    currency: 'Yen',
    code: 'JPN',
  },
  {
    id: 18,
    title: 'KOREA',
    currency: 'Won',
    code: 'KOR',
  },
  {
    id: 19,
    title: 'MEXICO',
    currency: 'Mexican Peso',
    code: 'MEX',
  },
  {
    id: 20,
    title: 'MALAYSIA',
    currency: 'Malaysian Ringgit',
    code: 'MYS',
  },
  {
    id: 21,
    title: 'NORWAY',
    currency: 'Norwegian Krone',
    code: 'NOR',
  },
  {
    id: 22,
    title: 'NEW ZEALAND',
    currency: 'New Zealand Dollar',
    code: 'NZL',
  },
  {
    id: 23,
    title: 'PHILIPPINES',
    currency: 'Philippine Peso',
    code: 'PHL',
  },
  {
    id: 24,
    title: 'POLAND',
    currency: 'Zloty',
    code: 'POL',
  },
  {
    id: 25,
    title: 'ROMANIA',
    currency: 'Romanian Leu',
    code: 'ROU',
  },
  {
    id: 26,
    title:'RUSSIAN FEDERATION',
    currency: 'Russian Ruble',
    code: 'RUS',
  },
  {
    id: 27,
    title:'SWEDEN',
    currency: 'Swedish Krona',
    code: 'SWE',
  },
  {
    id: 28,
    title:'SINGAPORE',
    currency: 'Singapore Dollar',
    code: 'SGP',
  },
  {
    id: 29,
    title:'THAILAND',
    currency: 'Baht',
    code: 'THA',
  },
  {
    id: 30,
    title:'TURKEY',
    currency: 'Turkish Lira',
    code: 'TUR',
  },
  {
    id: 31,
    title:'UNITED STATES OF AMERICA',
    currency: 'US Dollar',
    code: 'USA',
  },
  {
    id: 32,
    title:'SOUTH AFRICA',
    currency: 'Rand',
    code: 'ZAF',
  },
]

export default {
    country,
}